namespace Core.Models.Enums;

public record ItemEventActions
{
    public const string MOVE = "Move"; // worked
    public const string REMOVE = "Remove"; // worked
    public const string SPLIT = "Split"; // worked
    public const string MERGE = "Merge"; // worked
    public const string TRANSFER = "Transfer"; // worked
    public const string SWAP = "Swap"; // worked
    public const string FOLD = "Fold"; // worked
    public const string TOGGLE = "Toggle"; // worked
    public const string TAG = "Tag"; // worked
    public const string BIND = "Bind"; // worked
    public const string UNBIND = "Unbind"; // ??
    public const string EXAMINE = "Examine"; // worked
    public const string READ_ENCYCLOPEDIA = "ReadEncyclopedia"; // worked
    public const string APPLY_INVENTORY_CHANGES = "ApplyInventoryChanges"; // worked
    public const string CREATE_MAP_MARKER = "CreateMapMarker"; // worked
    public const string DELETE_MAP_MARKER = "DeleteMapMarker"; // worked
    public const string EDIT_MAP_MARKER = "EditMapMarker"; // Borked
    public const string OPEN_RANDOM_LOOT_CONTAINER = "OpenRandomLootContainer"; // worked
    public const string HIDEOUT_QTE_EVENT = "HideoutQuickTimeEvent"; // worked
    public const string SAVE_WEAPON_BUILD = "SaveWeaponBuild"; // this is an endpoint now?
    public const string REMOVE_WEAPON_BUILD = "RemoveWeaponBuild"; // this is an endpoint now?
    public const string REMOVE_BUILD = "RemoveBuild"; // this is an endpoint now?
    public const string SAVE_EQUIPMENT_BUILD = "SaveEquipmentBuild"; // this is an endpoint now?
    public const string REMOVE_EQUIPMENT_BUILD = "RemoveEquipmentBuild"; // this is an endpoint now?
    public const string REDEEM_PROFILE_REWARD = "RedeemProfileReward"; // ??
    public const string SET_FAVORITE_ITEMS = "SetFavoriteItems"; // worked
    public const string QUEST_FAIL = "QuestFail"; 
    public const string PIN_LOCK = "PinLock"; // worked
    public const string ADD_NOTE = "AddNote"; // worked
    public const string EDIT_NOTE = "EditNote"; // worked
    public const string DELETE_NOTE = "DeleteNote"; // worked
    public const string REPEATABLE_QUEST_CHANGE = "RepeatableQuestChange"; // worked
    public const string QUEST_HANDOVER = "QuestHandover";  // worked
    public const string QUEST_COMPLETE = "QuestComplete"; // worked
    public const string QUEST_ACCEPT = "QuestAccept"; // worked
    public const string RAGFAIR_RENEW_OFFER = "RagFairRenewOffer"; // worked
    public const string RAGFAIR_REMOVE_OFFER = "RagFairRemoveOffer"; // worked
    public const string RAGFAIR_ADD_OFFER = "RagFairAddOffer"; // worked
    public const string TRADER_REPAIR = "TraderRepair"; // worked
    public const string REPAIR = "Repair"; // worked
    public const string SELL_ALL_FROM_SAVAGE = "SellAllFromSavage";
    public const string RAGFAIR_BUY_OFFER = "RagFairBuyOffer"; // worked
    public const string TRADING_CONFIRM = "TradingConfirm"; // worked
    public const string BUY_FROM_TRADER = "buy_from_trader"; // worked
    public const string SELL_TO_TRADER = "sell_to_trader"; // worked
    public const string CHANGE_WISHLIST_ITEM_CATEGORY = "ChangeWishlistItemCategory"; // cant test till add works
    public const string REMOVE_FROM_WISHLIST = "RemoveFromWishList"; // cant test till add works
    public const string ADD_TO_WISHLIST = "AddToWishList"; // Borked
    public const string INSURE = "Insure"; // worked
    public const string RESTORE_HEALTH = "RestoreHealth";
    public const string HEAL = "Heal";
    public const string EAT = "Eat"; // worked
    public const string CUSTOMIZATION_SET = "CustomizationSet"; // worked
    public const string CUSTOMIZATION_BUY = "CustomizationBuy"; // worked
}
