// <auto-generated />
// This file is automatically generated. Do not modify manually.
// Any changes made to this file will be overwritten during the build process.

using SPTarkov.Server.Core.Models.Enums;

namespace SPTarkov.Server.Core.Utils;

public static partial class ProgramStatics
{
    private static string SptVersion { get; } = "4.0.0";
    private static string Commit { get; } = "a12b34";
    private static double BuildTime { get; } = 0000000000;
    private static EntryType BuildType { get; } = EntryType.LOCAL;
}
