<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build.props" />
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TestPrepatch</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SPTarkov.Reflection\SPTarkov.Reflection.csproj" />
  </ItemGroup>
  <Target Name="CopyToServerPatchers" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <OutputDLL Include="$(ProjectDir)$(OutDir)$(TargetName).dll" />
    </ItemGroup>
    <Copy
      SourceFiles="@(OutputDLL)"
      DestinationFolder="$(MSBuildProjectDirectory)\..\..\SPTarkov.Server\bin\$(Configuration)\net10.0\user\patchers\com.sp-tarkov.test-mod2"
    />
  </Target>
</Project>
