namespace Core.Models.Enums;

public enum EquipmentSlots
{
    HEADWEAR,
    EARPIECE,
    FACE_COVER,
    ARMOR_VEST,
    EYEWEAR,
    ARM_BAND,
    TACTICAL_VEST,
    POCKETS,
    BACKPACK,
    SECURED_CONTAINER,
    FIRST_PRIMARY_WEAPON,
    SECOND_PRIMARY_WEAPON,
    HOLSTER,
    SCABBARD
}