name: .NET Format

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BYPASS_WORKFLOW_PAT }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore Tool Dependencies
        run: dotnet tool install -g csharpier

      - name: CSharpier Format
        run: dotnet csharpier format .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: .NET Format Style Fixes
          commit_user_name: Format Bot
